--_new(_class_player, _image.pl00, _quad_group.pl00_normal, _quad_group.pl00_left, _quad_group.pl00_right, _quad_group.pl00_leftex, _quad_group.pl00_rightex, 3, 10,5)
--_new(_class_drawable_ui, _image.titlebg)
--local o = _newex(_do_script('res.player.paradox_state'), {x = 100, y = 100})
--o:set_content(100)
